
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRLIT = 46;
  public static final int LTE = 22;
  public static final int CHAR = 40;
  public static final int UMINUS = 50;
  public static final int UPLUS = 49;
  public static final int LPAREN = 31;
  public static final int SEMI = 29;
  public static final int INT = 41;
  public static final int PRINTLN = 11;
  public static final int MINUS = 18;
  public static final int RPAREN = 32;
  public static final int LSQR = 35;
  public static final int NOT = 14;
  public static final int AND = 5;
  public static final int INTLIT = 47;
  public static final int LT = 20;
  public static final int OR = 6;
  public static final int BOOL = 44;
  public static final int COMMA = 30;
  public static final int CLASS = 2;
  public static final int INC = 12;
  public static final int DIV = 16;
  public static final int PLUS = 17;
  public static final int ASSIGN = 37;
  public static final int IF = 25;
  public static final int ID = 3;
  public static final int EOF = 0;
  public static final int RETURN = 28;
  public static final int TRUE = 7;
  public static final int error = 1;
  public static final int LCURLY = 33;
  public static final int VOID = 43;
  public static final int FLOATLIT = 48;
  public static final int EQ = 19;
  public static final int GTE = 23;
  public static final int RCURLY = 34;
  public static final int CHARLIT = 45;
  public static final int COLON = 38;
  public static final int ELSE = 26;
  public static final int READ = 9;
  public static final int RSQR = 36;
  public static final int FINAL = 39;
  public static final int WHILE = 27;
  public static final int FLOAT = 42;
  public static final int NE = 24;
  public static final int MULTI = 15;
  public static final int QUESTION = 4;
  public static final int DEC = 13;
  public static final int FALSE = 8;
  public static final int GT = 21;
  public static final int PRINT = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "ID",
  "QUESTION",
  "AND",
  "OR",
  "TRUE",
  "FALSE",
  "READ",
  "PRINT",
  "PRINTLN",
  "INC",
  "DEC",
  "NOT",
  "MULTI",
  "DIV",
  "PLUS",
  "MINUS",
  "EQ",
  "LT",
  "GT",
  "LTE",
  "GTE",
  "NE",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "LSQR",
  "RSQR",
  "ASSIGN",
  "COLON",
  "FINAL",
  "CHAR",
  "INT",
  "FLOAT",
  "VOID",
  "BOOL",
  "CHARLIT",
  "STRLIT",
  "INTLIT",
  "FLOATLIT",
  "UPLUS",
  "UMINUS"
  };
}

